### ISSUE TITLE
Multiples connections

### ISSUE THREAD

**Issue by cartifon** [cobrowseio/cobrowse-agent-sdk-examples#1]
Hey guys, I have a question.

Is is possible to have multiples connections on the client for the co-browse? 

The idea would be to have more than one person connecting to the same client.

Something like 

Agent 1 -> Connected to guest 1
Agent 2 -> Connected to guest 1

So, in two different browsers, I would be connected to the same co-browse....

**Comment by snyderj** [comment]
Thanks for the question. 

From our web dashboard, you can have a 2nd agent connect to an existing session from https://cobrowse.io/dashboard/history. 

You'll notice from the syntax of the link that all that is required is the session id (as well as the agent being authenticated to the same account): 
https://cobrowse.io/session/cJzjIgY4T0x-ebOS6992vA

So, the same should be available programmatically via our Agent SDK. 

Please email us if you have any follow-up questions on this use case, and we would be happy to help. Thanks!

**Comment by cartifon** [comment]
Hey John,  

So, how would I connect the second agent programmatically? What are the APIs call that I should make? 

Do you guys have any example of that? I was not able to find anything like that on the documentation for the Agent SDK.

**Comment by snyderj** [comment]
As mentioned in our previous reply, we will follow-up via email thanks.
